version: 2
registries:
    npm-github:
        type: npm-registry
        url: https://npm.pkg.github.com
        token: ${{secrets.READ_BAHAIORG_PACKAGES}}
updates:
    - package-ecosystem: npm
      directory: /
      schedule:
          interval: weekly
      commit-message:
          prefix: chore
          include: scope
      ignore:
          - dependency-name: "@types/node"
            update-types: ["version-update:semver-major"] # major version should only be incremented when we change Node versions
      registries:
          - npm-github
      groups:
          non-major-revisions:
              update-types:
                  - minor
                  - patch
          major-revisions:
              update-types:
                  - major
